---
- name: 'Ensure dotfiles repository is cloned locally.'
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_destination }}"
    key_file: "{{ github_ssh_key_path }}"
    accept_hostkey: yes
    ssh_opts: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o HashKnownHosts=no'
    force: yes

- name: 'Install Dotfiles.'
  ansible.builtin.command:
    cmd: './install'
    chdir: "{{ dotfiles_destination }}"
